fix: add TARGETARCH default and validation in Dockerfile.k8s

diff --git a/Dockerfile.k8s b/Dockerfile.k8s
--- a/Dockerfile.k8s
+++ b/Dockerfile.k8s
@@ -1,6 +1,6 @@
 FROM golang:1.25.5 AS builder
 
-ARG TARGETARCH
+ARG TARGETARCH=amd64
 
 RUN apt-get update && apt-get install -y clang lld wget
 
@@ -9,6 +9,7 @@ RUN wget https://github.com/vultisig/go-wrappers/archive/refs/heads/master.tar.g
     cd go-wrappers-master && \
     mkdir -p /usr/local/lib/dkls/includes && \
     cp includes/go-dkls.h includes/go-schnorr.h /usr/local/lib/dkls/includes/ && \
+    if [ ! -d "includes/linux-${TARGETARCH}" ]; then echo "Error: includes/linux-${TARGETARCH} not found" && exit 1; fi && \
     cp -r includes/linux-${TARGETARCH} /usr/local/lib/dkls/includes/linux
 
 ARG SERVICE
